# Ansible Inventory for Azure VMs
# Make sure VMs are running and NSG allows your IP

[azure_vms]
vm-ubuntu-1 ansible_host=4.206.179.108 ansible_user=azureuser ansible_ssh_private_key_file=~/.ssh/azure_lab_key
vm-ubuntu-2 ansible_host=4.206.104.3 ansible_user=azureuser ansible_ssh_private_key_file=~/.ssh/azure_lab_key
vm-ubuntu-3 ansible_host=4.206.27.56 ansible_user=azureuser ansible_ssh_private_key_file=~/.ssh/azure_lab_key

[azure_vms:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_python_interpreter=/usr/bin/python3

[all:vars]
ansible_connection=ssh
ansible_port=22
ansible_become=yes
ansible_become_method=sudo
ansible_become_user=root